version: "3.9"
services:
  nginx:
    build: containers/nginx
    environment:
      TZ: Asia/Tokyo
    volumes:
      - nginxsocket:/keiba_expectation_app/tmp/sockets
      - static-content:/keiba_expectation_app/public
      - ./containers/nginx/ssl:/etc/nginx/ssl
    ports: 
      - "80:80"
      - "443:443"
    depends_on: 
      - web
  web:
    build: .
    environment:
      TZ: Asia/Tokyo
    env_file: development.env
    command: bash -c "yarn install --check-files && bundle exec puma -C config/puma.rb"
    volumes:
      - .:/keiba_expectation_app
      - dbsocket:/var/run/mysqld
      - nginxsocket:/keiba_expectation_app/tmp/sockets
      - static-content:/keiba_expectation_app/public
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      TZ: Asia/Tokyo
    env_file: development.env
    ports:
      - '3316:3306'
    volumes:
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/sql:/docker-entrypoint-initdb.d
      - mysql-db:/var/lib/mysql
      - dbsocket:/var/run/mysqld
# Volume Container
## Host側は、var/lib/docker/volumes/<Volume 名(以下では mysql-db)> にデータを永続化
volumes:
  mysql-db:
    driver: local
  dbsocket:
  nginxsocket:
  static-content: